/**
 * Shared types for booking and pricing services
 * Ensures consistency between frontend vehicle types and backend vehicle tiers
 *
 * Matches backend BookingRequest.java exactly.
 * Note: bookingId === rideId (same UUID PK). No separate rideId field exists.
 */

import { VehicleTier } from './pricingService';

export type { VehicleTier };

/** Coordinates object matching backend BookingRequest.pickupCoordinates / dropoffCoordinates */
export interface Coordinates {
  lat: number;
  lng: number;
}

/**
 * Payload for creating a booking — matches backend BookingRequest.java exactly.
 *
 * Backend source: booking-service/.../dto/request/BookingRequest.java
 * Gateway: POST /api/v1/bookings
 */
export interface CreateBookingPayload {
  pickupLocation: string;
  dropoffLocation: string;
  customerNote?: string;
  pickupCoordinates: Coordinates;
  dropoffCoordinates: Coordinates;
  vehicleType: VehicleTier;
  paymentMethod: 'CASH' | 'MOMO' | 'ZALOPAY' | 'VNPAY' | 'SEPAY';
  estimatedFare: number;
  discountAmount?: number;
  promoCode?: string;
  /** From Pricing-Service estimate response (required for quote verification) */
  estimateId?: string;
  /** From Pricing-Service estimate response (required for quote verification) */
  quoteId?: string;
  /** SHA-256 hash of quote payload */
  quotePayloadHash?: string;
  /** Hash algorithm, default SHA-256 */
  quoteHashAlgorithm?: string;
  /** ISO 8601 timestamp — quote expiry */
  quoteExpiresAt?: string;
  /** Legacy field */
  quoteToken?: string;
  /** Auto-generated by FE for idempotency */
  idempotencyKey?: string;
}
